[[hosts]]
name = "puffy"
ip = "10.69.42.1"

[hosts.system]
networking.hostName = "puffy"
nixpkgs.system = "aarch64-linux"
services.cockroachdb.locality = "location=biden"
services.seaweedfs.volumes.dot.dataCenter = "biden"
services.seaweedfs.volumes.dot.rack = "dot"
services.seaweedfs.filers.dot.dataCenter = "biden"
services.seaweedfs.filers.dot.rack = "dot"
dot.vpn.coordinator = true
dot.vpn.ip = "10.69.42.1"
dot.vpn.subnet.ip = "10.69.42.0"
dot.vpn.subnet.bits = 24
dot.vpn.subnet.mask = "255.255.255.0"
dot.ddns.coordinator = true
dot.consul.coordinator = true
dot.traefik.coordinator = true
dot.postgres.coordinator = true
dot.fs.coordinator = true
dot.vault.coordinator = true
dot.vaultwarden.coordinator = true
dot.miniflux.coordinator = true
dot.hardware.rpi."4".enable = true
dot.hardware.temp = "/sys/class/hwmon/hwmon0/temp1_input"

[hosts.home]
dot.hardware.rpi."4".enable = true
dot.hardware.temp = "/sys/class/hwmon/hwmon0/temp1_input"

[[hosts]]
name = "brock"
ip = "10.69.42.5"

[hosts.system]
networking.hostName = "brock"
nixpkgs.system = "aarch64-linux"
services.cockroachdb.locality = "location=biden"
services.seaweedfs.volumes.dot.dataCenter = "biden"
services.seaweedfs.volumes.dot.rack = "dot"
services.seaweedfs.filers.dot.dataCenter = "biden"
services.seaweedfs.filers.dot.rack = "dot"
dot.vpn.coordinator = true
dot.vpn.ip = "10.69.42.5"
dot.vpn.subnet.ip = "10.69.42.0"
dot.vpn.subnet.bits = 24
dot.vpn.subnet.mask = "255.255.255.0"
dot.ddns.coordinator = true
dot.consul.coordinator = true
dot.traefik.coordinator = true
dot.postgres.coordinator = true
dot.fs.coordinator = true
dot.vault.coordinator = true
dot.vaultwarden.coordinator = true
dot.miniflux.coordinator = true
dot.hardware.rpi."4".enable = true
dot.hardware.temp = "/sys/class/hwmon/hwmon0/temp1_input"

[hosts.home]
dot.hardware.rpi."4".enable = true
dot.hardware.temp = "/sys/class/hwmon/hwmon0/temp1_input"

[[hosts]]
name = "bean"
ip = "10.69.42.6"

[hosts.system]
networking.hostName = "bean"
nixpkgs.system = "aarch64-linux"
services.cockroachdb.locality = "location=biden"
services.seaweedfs.volumes.dot.dataCenter = "biden"
services.seaweedfs.volumes.dot.rack = "dot"
services.seaweedfs.filers.dot.dataCenter = "biden"
services.seaweedfs.filers.dot.rack = "dot"
dot.vpn.coordinator = true
dot.vpn.ip = "10.69.42.6"
dot.vpn.subnet.ip = "10.69.42.0"
dot.vpn.subnet.bits = 24
dot.vpn.subnet.mask = "255.255.255.0"
dot.ddns.coordinator = true
dot.consul.coordinator = true
dot.traefik.coordinator = true
dot.postgres.coordinator = true
dot.fs.coordinator = true
dot.vault.coordinator = true
dot.vaultwarden.coordinator = true
dot.miniflux.coordinator = true
dot.hardware.rpi."4".enable = true
dot.hardware.temp = "/sys/class/hwmon/hwmon0/temp1_input"

[hosts.home]
dot.hardware.rpi."4".enable = true
dot.hardware.temp = "/sys/class/hwmon/hwmon0/temp1_input"

[[hosts]]
name = "workbug"
ip = "10.69.42.3"

[hosts.system]
networking.hostName = "workbug"
nixpkgs.system = "x86_64-linux"
services.cockroachdb.locality = "location=portable"
services.seaweedfs.volumes.dot.dataCenter = "portable"
services.seaweedfs.volumes.dot.rack = "dot"
services.seaweedfs.filers.dot.dataCenter = "portable"
services.seaweedfs.filers.dot.rack = "dot"
dot.vpn.ip = "10.69.42.3"
dot.vpn.subnet.ip = "10.69.42.0"
dot.vpn.subnet.bits = 24
dot.vpn.subnet.mask = "255.255.255.0"
dot.hardware.temp = "/sys/class/hwmon/hwmon3/temp1_input"
dot.hardware.monitor.main = "eDP-1"
dot.hardware.battery.enable = true
dot.pass = false

[hosts.home]
dot.prompt.nsfw = false
dot.hardware.temp = "/sys/class/hwmon/hwmon3/temp1_input"
dot.hardware.monitor.main = "eDP-1"
dot.hardware.battery.enable = true
dot.wallpaper.static = true
dot.pass = false

[[hosts]]
name = "koncar9000"
ip = "10.69.42.7"

[hosts.system]
networking.hostName = "koncar9000"
nixpkgs.system = "x86_64-linux"
services.cockroachdb.locality = "location=portable"
services.seaweedfs.volumes.dot.dataCenter = "portable"
services.seaweedfs.volumes.dot.rack = "dot"
services.seaweedfs.filers.dot.dataCenter = "portable"
services.seaweedfs.filers.dot.rack = "dot"
dot.vpn.ip = "10.69.42.7"
dot.vpn.subnet.ip = "10.69.42.0"
dot.vpn.subnet.bits = 24
dot.vpn.subnet.mask = "255.255.255.0"
# dot.hardware.temp = "/sys/class/hwmon/hwmon3/temp1_input"
# dot.hardware.monitor.main = "eDP-1"
dot.pass = false

[hosts.home]
# dot.hardware.temp = "/sys/class/hwmon/hwmon3/temp1_input"
# dot.hardware.monitor.main = "eDP-1"
dot.wallpaper.static = true
dot.pass = false

[[hosts]]
name = "hearth"
ip = "10.69.42.2"

[hosts.system]
networking.hostName = "hearth"
nixpkgs.system = "x86_64-linux"
services.cockroachdb.locality = "location=biden"
services.seaweedfs.volumes.dot.dataCenter = "biden"
services.seaweedfs.volumes.dot.rack = "dot"
services.seaweedfs.filers.dot.dataCenter = "biden"
services.seaweedfs.filers.dot.rack = "dot"
boot.blacklistedKernelModules = ["amdgpu", "radeon"]
dot.gc = false
dot.vpn.ip = "10.69.42.2"
dot.vpn.subnet.ip = "10.69.42.0"
dot.vpn.subnet.bits = 24
dot.vpn.subnet.mask = "255.255.255.0"
dot.hardware.temp = "/sys/class/hwmon/hwmon2/temp1_input"
dot.hardware.monitor.main = "DP-1"
dot.pass = false

[hosts.home]
services.easyeffects.preset = "krk"
dot.hardware.temp = "/sys/class/hwmon/hwmon2/temp1_input"
dot.hardware.monitor.main = "DP-1"
dot.pass = false

[[hosts]]
name = "officer"
ip = "10.69.42.4"

[hosts.system]
networking.hostName = "officer"
nixpkgs.system = "x86_64-linux"
services.cockroachdb.locality = "location=veslaja"
services.seaweedfs.volumes.dot.dataCenter = "veslaja"
services.seaweedfs.volumes.dot.rack = "dot"
services.seaweedfs.filers.dot.dataCenter = "veslaja"
services.seaweedfs.filers.dot.rack = "dot"
dot.vpn.ip = "10.69.42.4"
dot.vpn.subnet.ip = "10.69.42.0"
dot.vpn.subnet.bits = 24
dot.vpn.subnet.mask = "255.255.255.0"
dot.hardware.temp = "/sys/class/hwmon/hwmon0/temp1_input"
dot.hardware.monitor.main = "DVI-D-0"
dot.pass = false

[hosts.home]
dot.prompt.nsfw = false
dot.hardware.temp = "/sys/class/hwmon/hwmon0/temp1_input"
dot.hardware.monitor.main = "DVI-D-0"
dot.pass = false
