keys:
  - &mess age1kenfnysyt7w7nq0nnvnlqrrn40unkphts4ycuxd5lv7679t9pejqnh8twf
  - &pi age16fvhjve0x8cv82qdr6hjke9ftr3lsy7muue8f6x0dzjnjfg5fdysekgd06
creation_rules:
  - path_regex: /dev/stdin
    key_groups:
    - age:
       - *mess
       - *pi
