git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never

customCommands:
  - key: '<c-c>'
    description: 'commit with supermodules'
    prompts:
      - type: 'input'
        title: 'Message'
    command: >-
      git commit -m "{{index .PromptResponses 0}}" &&
      wd=$(pwd) &&
      mod="$(git rev-parse --show-toplevel)" &&
      cd "$mod" &&
      cd .. &&
      sup="$(git rev-parse --show-toplevel)" &&
      cd "$sup" &&
      mod="$(realpath --relative-to="$sup" "$mod")" &&
      git add "$mod" &&
      git commit -m "update module $mod" &&
      cd "$wd"
    subprocess: true
    context: 'global'

  - key: '<c-p>'
    description: 'push with supermodules'
    command: >-
      git push &&
      wd=$(pwd) &&
      mod="$(git rev-parse --show-toplevel)" &&
      cd "$mod" &&
      cd .. &&
      sup="$(git rev-parse --show-toplevel)" &&
      cd "$sup" &&
      git push &&
      cd "$wd"
    subprocess: true
    context: 'global'
