format = """\
[╭─](bold bright-cyan)\
$username[@](bold bright-cyan)$hostname \
[using](white italic) $shlvl[$shell](bold dimmed red)\

$singularity\
$kubernetes\
$docker_context\

$package\
$cmake\
$cobol\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$aws\
$gcloud\
$openstack\
$crystal\

$jobs\
$cmd_duration$status \

$battery$memory_usage\

$line_break\

[│](bold cyan)   \
[in](white italic) $directory$vcsh\
$git_branch$hg_branch\
$git_commit$git_state$git_metrics$git_status\
$time\
$line_break\

[╰─](bold dimmed cyan)\
"""

scan_timeout = 500
command_timeout = 500
add_newline = true


[username]
format = "[$user]($style)"
style_user = "bold bright-purple"
style_root = "bold bright-red"
show_always = true

[hostname]
format = "[$hostname]($style)"
style = "bold purple"
trim_at = "-"
ssh_only = false
disabled = false

[shell]
fish_indicator = ""
bash_indicator = '\$'
zsh_indicator = 'Z'
disabled = false

[shlvl]
threshold = 2
format = "[$symbol]($style) "
symbol = "↓"
repeat = true
style = "dimmed yellow"
disabled = false

# TODO: change verb style to white italic on these

[aws]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[golang]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "

[cmake]
symbol = " "

# TODO: fix
[lua]
symbol = "⯟"

[cmd_duration]
min_time = 1
format = "[took](white italic) [$duration]($style)"
disabled = false
style = "bold bright-yellow"

[status]
symbol = ""
style = "bright red"
format = """ \
[[{](bold cyan)\
$symbol\
$status_common_meaning\
$status_signal_name\
$status_maybe_int\
[}](bold cyan)]\
($style)"""
map_symbol = true
disabled = false


[directory]
style = "bold blue"
truncation_length = 3
truncate_to_repo = true

[git_branch]
format = "[on](italic dimmed white) [$symbol $branch]($style)"
style = "bold blue"
symbol = ""

[hg_branch]
format = "[on](italic dimmed white) [$symbol $branch]($style)"
style = "bold blue"
symbol = ""

[git_status]
style = "bold bright-yellow"
format = """ \
[[{](bold cyan)\
$all_status\
$ahead_behind\
[}](bold cyan)]\
($style)"""
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
deleted = "x"


[character]
success_symbol = "[λ](bold green)"
vicmd_symbol = "[](bold green)"
error_symbol = "[](bold bright-red)"

[[battery.display]]
threshold = 20
