[vpn]
ip = "10.69.42.0"
bits = 24
mask = "255.255.255.0"

[[hosts]]
name = "puffy"
ip = "10.69.42.1"

[hosts.system]
networking.hostName = "puffy"
nixpkgs.system = "aarch64-linux"
services.cockroachdb.locality = "location=biden"
dot.vpn.coordinator = true
dot.vpn.ip = "10.69.42.1"
dot.vpn.subnet.ip = "10.69.42.0"
dot.vpn.subnet.bits = 24
dot.vpn.subnet.mask = "255.255.255.0"
dot.ddns.coordinator = true
dot.postgres.coordinator = true
dot.vault.coordinator = true
dot.vaultwarden.coordinator = true
dot.hardware.rpi."4".enable = true
dot.hardware.temp = "/sys/class/hwmon/hwmon0/temp1_input"

[hosts.home]
dot.hardware.rpi."4".enable = true
dot.hardware.temp = "/sys/class/hwmon/hwmon0/temp1_input"

[[hosts]]
name = "brock"
ip = "10.69.42.5"

[hosts.system]
networking.hostName = "brock"
nixpkgs.system = "aarch64-linux"
services.cockroachdb.locality = "location=biden"
dot.vpn.coordinator = true
dot.vpn.ip = "10.69.42.5"
dot.vpn.subnet.ip = "10.69.42.0"
dot.vpn.subnet.bits = 24
dot.vpn.subnet.mask = "255.255.255.0"
dot.ddns.coordinator = true
dot.postgres.coordinator = true
dot.vault.coordinator = true
dot.vaultwarden.coordinator = true
dot.hardware.rpi."4".enable = true
dot.hardware.temp = "/sys/class/hwmon/hwmon0/temp1_input"

[hosts.home]
dot.hardware.rpi."4".enable = true
dot.hardware.temp = "/sys/class/hwmon/hwmon0/temp1_input"

[[hosts]]
name = "workbug"
ip = "10.69.42.3"

[hosts.system]
networking.hostName = "workbug"
nixpkgs.system = "x86_64-linux"
services.cockroachdb.locality = "location=portable"
dot.vpn.ip = "10.69.42.3"
dot.vpn.subnet.ip = "10.69.42.0"
dot.vpn.subnet.bits = 24
dot.vpn.subnet.mask = "255.255.255.0"
dot.hardware.temp = "/sys/class/hwmon/hwmon3/temp1_input"
dot.hardware.monitor.main = "eDP-1"
dot.pass = false

[hosts.home]
dot.prompt.nsfw = false
dot.hardware.temp = "/sys/class/hwmon/hwmon3/temp1_input"
dot.hardware.monitor.main = "eDP-1"
dot.wallpaper.static = true
dot.pass = false

[[hosts]]
name = "hearth"
ip = "10.69.42.2"

[hosts.system]
networking.hostName = "hearth"
nixpkgs.system = "x86_64-linux"
services.cockroachdb.locality = "location=biden"
dot.gc = false
dot.vpn.ip = "10.69.42.2"
dot.vpn.subnet.ip = "10.69.42.0"
dot.vpn.subnet.bits = 24
dot.vpn.subnet.mask = "255.255.255.0"
dot.hardware.temp = "/sys/class/hwmon/hwmon2/temp1_input"
dot.hardware.monitor.main = "DP-1"
dot.pass = false

[hosts.home]
services.easyeffects.preset = "krk"
dot.hardware.temp = "/sys/class/hwmon/hwmon2/temp1_input"
dot.hardware.monitor.main = "DP-1"
dot.pass = false

[[hosts]]
name = "officer"
ip = "10.69.42.4"

[hosts.system]
networking.hostName = "officer"
nixpkgs.system = "x86_64-linux"
services.cockroachdb.locality = "location=veslaja"
dot.vpn.ip = "10.69.42.4"
dot.vpn.subnet.ip = "10.69.42.0"
dot.vpn.subnet.bits = 24
dot.vpn.subnet.mask = "255.255.255.0"
dot.hardware.temp = "/sys/class/hwmon/hwmon0/temp1_input"
dot.hardware.monitor.main = "DVI-D-0"
dot.pass = false

[hosts.home]
dot.prompt.nsfw = false
dot.hardware.temp = "/sys/class/hwmon/hwmon0/temp1_input"
dot.hardware.monitor.main = "DVI-D-0"
dot.pass = false
