#!/usr/bin/env bash
set -eo pipefail;

abs() { echo "$(cd "$(dirname "$1")" && pwd)/$(basename "$1")"; }
SCRIPTS="$(abs "$(dirname "${BASH_SOURCE[0]}")")";
ROOT="$(abs "$(dirname "$SCRIPTS")")";

ARTIFACTS="$ROOT/artifacts";

mkdir -p "$ARTIFACTS";

echo "Generating Intermediate CA...";
openssl genpkey -algorithm ED25519 \
  -out "$ARTIFACTS/ca.key";
openssl req -new -key "$ARTIFACTS/ca.key" \
  -out "$ARTIFACTS/ca.csr" \
  -subj "/CN=Mess Raspberry Pi Intermediate CA";
openssl x509 -req -in "$ARTIFACTS/ca.csr" \
  -CA "$ARTIFACTS/root-ca.crt" \
  -CAkey "$ARTIFACTS/root-ca.key" \
  -CAcreateserial \
  -out "$ARTIFACTS/ca.crt" \
  -days 3650;

echo "Generating passwords...";
POSTGRES_PASSWORD="$(openssl rand -base64 32)";
MESS_PASSWORD="$(openssl rand -base64 32)";
cat > "$ARTIFACTS/alter-passwords.sql" <<EOF
ALTER USER postgres WITH PASSWORD '$POSTGRES_PASSWORD';
ALTER USER mess WITH PASSWORD '$MESS_PASSWORD';
EOF

echo "Building Raspberry Pi image...";
wd="$(abs "$(pwd)")";
cd "$ROOT";
nix build ".#nixosConfigurations.raspberry-pi.config.system.build.sdImage";
cd "$wd";

echo "Done!";

