#!/usr/bin/env bash
set -eo pipefail

SECRETS="$1"
if [[ ! -d "$SECRETS" ]]; then
  printf "Please enter a secrets directory\n"
  exit 1
fi

SERVER="$2"
if [[ "$SERVER" == "" ]]; then
  printf "Please enter a valid server\n"
  exit 1
fi

CLIENT="$3"
if [[ "$CLIENT" == "" ]]; then
  printf "Please enter a valid client\n"
  exit 1
fi

mkdir -p "$SECRETS"
ID="$(openssl rand -hex 16)"
NOW="$(date --utc -Iseconds)"
ID_SECRETS="$SECRETS/vpn/$NOW-$ID"
if [[ -d "$ID_SECRETS" ]]; then
  printf "Device secrets already exist! Please try again..."
  exit 1
fi
mkdir -p "$ID_SECRETS"
SERVER_SECRETS="$SECRETS/$SERVER"
mkdir -p "$SERVER_SECRETS"
CLIENT_SECRETS="$SECRETS/$CLIENT"
mkdir -p "$CLIENT_SECRETS"
printf "%s" "$ID" >"$ID_SECRETS/client.id.pub"
cp "$ID_SECRETS/client.id.pub" "$CLIENT_SECRETS/client.id.pub"

mkserver() {
  local name

  name="$1"

  cp "$ID_SECRETS/$name" "$SERVER_SECRETS/$name"
}

mkclient() {
  local name

  name="$1"

  cp "$ID_SECRETS/$name" "$CLIENT_SECRETS/$name"
}

mkid() {
  local name

  name="$1"

  # NOTE: if you do it raw it adds a newline
  printf "%s" "$(openssl rand -base64 32)" >"$ID_SECRETS/$name.id.pub"
}

mkpass() {
  local name

  name="$1"

  # NOTE: if you do it raw it adds a newline
  passwd="$(openssl rand -base64 32)"
  printf "%s" "$passwd" >"$ID_SECRETS/$name.pass"
  chmod 400 "$ID_SECRETS/$name.pass"
  printf "%s" "$(echo "$passwd" | mkpasswd --stdin)" >"$ID_SECRETS/$name.pass.pub"
}

mkage() {
  local name

  name="$1"

  age-keygen -o "$ID_SECRETS/$name.age" 2>&1 |
    awk '{ print $3 }' >"$ID_SECRETS/$name.age.pub"
  chmod 400 "$ID_SECRETS/$name.age"
}

mkssh() {
  local name
  local comment

  if [[ "$2" == "" ]]; then
    name="$1"

    ssh-keygen -q -a 100 -t ed25519 -N "" \
      -f "$ID_SECRETS/$name.ssh"
  else
    name="$1"
    comment="$2"

    ssh-keygen -q -a 100 -t ed25519 -N "" \
      -C "$comment" \
      -f "$ID_SECRETS/$name.ssh"
  fi

  chmod 400 "$ID_SECRETS/$name.ssh"
}

mkssl() {
  local name
  local ca
  local subj

  if [[ "$3" == "" ]]; then
    name="$1"
    subj="$2"

    openssl genpkey -algorithm ED25519 \
      -out "$ID_SECRETS/$name.ssl.key" >/dev/null 2>&1
    openssl req -x509 \
      -key "$ID_SECRETS/$name.ssl.key" \
      -out "$ID_SECRETS/$name.ssl.crt" \
      -subj "/CN=$subj" \
      -days 3650 >/dev/null 2>&1
  else
    name="$1"
    ca="$2"
    subj="$3"

    openssl genpkey -algorithm ED25519 \
      -out "$ID_SECRETS/$name.ssl.key" >/dev/null 2>&1
    openssl req -new \
      -key "$ID_SECRETS/$name.ssl.key" \
      -out "$ID_SECRETS/$name.ssl.csr" \
      -subj "/CN=$subj" >/dev/null 2>&1
    openssl x509 -req \
      -in "$ID_SECRETS/$name.ssl.csr" \
      -CA "$ca.ssl.crt" \
      -CAkey "$ca.ssl.key" \
      -CAcreateserial \
      -out "$ID_SECRETS/$name.ssl.crt" \
      -days 3650 >/dev/null 2>&1
  fi

  chmod 400 "$ID_SECRETS/$name.ssl.key"
}

mkparam() {
  local name

  name="$1"

  openssl dhparam -out "$ID_SECRETS/$name.dhparam.pem"
}

mktakey() {
  local name

  name="$1"

  openvpn --genkey --secret "$ID_SECRETS/$name.ta.key"
}

indent() {
  local text
  local amount

  text="$1"
  amount="$2"

  printf "%b" "$text" |
    sed -z "s/\\n/,/g;s/,/\\n$(printf "%${amount}s" "")/g"
}

mkage "secrets"
mkserver "secrets.age"
mkserver "secrets.age.pub"

mkssl "root-ca" "Mikoshi Root CA"
mkserver "root-ca.ssl.key"
mkserver "root-ca.ssl.crt"

mkage "mikoshi"
mkserver "mikoshi.age"
mkserver "mikoshi.age.pub"

mkssh "mikoshi"
mkserver "mikoshi.ssh"
mkserver "mikoshi.ssh.pub"

mkssl "mikoshi" "$SERVER_SECRETS/root.ssl" "Mikoshi Cert"
mkserver "mikoshi.ssl.key"
mkserver "mikoshi.ssl.csr"
mkserver "mikoshi.ssl.crt"

mkparam "mikoshi"
mkserver "mikoshi.dhparam.pem"

mktakey "mikoshi"
mkserver "mikoshi.ta.key"

mkage "client"
mkclient "client.age"
mkclient "client.age.pub"

mkpass "client"
mkclient "client.pass.pub"

mkssl "client" "$SERVER_SECRETS/root.ssl" "Client-$ID Cert"
mkclient "client.ssl.key"
mkclient "client.ssl.csr"
mkclient "client.ssl.crt"
