"type" = "textAlternate"
"constant" = "text"
"constant.builtin" = { fg = "textAlternate", modifiers = ["italic"] }
"constant.builtin.boolean" = "textAlternate"
"constant.numeric" = "textAlternate"
"constant.character.escape" = "textAlternate"
"string" = "textAlternate"
"string.regexp" = "textAlternate"
"string.special" = "textAlternate"
"comment" = { fg = "textAlternate", modifiers = ["italic"] }
"variable" = "text"
"variable.builtin" = { fg = "textAlternate", modifiers = ["italic"] }
"variable.parameter" = "text"
"variable.other.member" = "textAlternate"
"label" = "textAlternate"
"punctuation" = "textAlternate"
"punctuation.delimiter" = "textAlternate"
"punctuation.bracket" = "text"
"punctuation.special" = "textAlternate"
"keyword" = "textAlternate"
"keyword.operator" = "textAlternate"
"keyword.directive" = "textAlternate"
"keyword.storage" = "textAlternate"
"operator" = "textAlternate"
"function" = "textAlternate"
"function.macro" = "textAlternate"
"tag" = "textAlternate"
"namespace" = { fg = "textAlternate", modifiers = ["italic"] }
"attribute" = { fg = "textAlternate", modifiers = ["italic"] }
"constructor" = "textAlternate"
"module" = "textAlternate"
"special" = "textAlternate"

"markup.heading.marker" = "textAlternate"
"markup.heading.1" = { fg = "textAlternate", modifiers = ["bold"] }
"markup.heading.2" = { fg = "textAlternate", modifiers = ["bold"] }
"markup.heading.3" = { fg = "textAlternate", modifiers = ["bold"] }
"markup.heading.4" = { fg = "textAlternate", modifiers = ["bold"] }
"markup.heading.5" = { fg = "textAlternate", modifiers = ["bold"] }
"markup.heading.6" = { fg = "textAlternate", modifiers = ["bold"] }
"markup.list" = "textAlternate"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "textAlternate", underline = { style = "line" } }
"markup.link.label" = "textAlternate"
"markup.link.text" = "textAlternate"
"markup.quote" = "textAlternate"
"markup.raw.inline" = "textAlternate"
"markup.raw.block" = "textAlternate"

"diff.plus" = "textAlternate"
"diff.delta" = "textAlternate"
"diff.minus" = "textAlternate"

"ui.background" = {}
"ui.background.separator" = "backgroundAlternate"
"ui.cursor" = { fg = "backgroundAlternate", bg = "textAlternate" }
"ui.cursor.insert" = { fg = "background", bg = "textAlternate" }
"ui.cursor.select" = { fg = "background", bg = "textAlternate" }
"ui.cursor.match" = { fg = "textAlternate", bg = "backgroundAlternate" }
"ui.cursor.primary" = { fg = "background", bg = "text" }
"ui.cursorline.primary" = { bg = "backgroundAlternate" }
"ui.cursorline.secondary" = { bg = "backgroundAlternate" }
"ui.selection" = { bg = "backgroundAlternate" }
"ui.linenr" = "textAlternate"
"ui.linenr.selected" = "textAlternate"
"ui.statusline" = { fg = "text" }
"ui.statusline.inactive" = { fg = "textAlternate", bg = "backgroundAlternate" }
"ui.statusline.normal" = { fg = "background", bg = "primary", modifiers = [
  "bold",
] }
"ui.statusline.insert" = { fg = "background", bg = "secondary", modifiers = [
  "bold",
] }
"ui.statusline.select" = { fg = "background", bg = "textAlternate", modifiers = [
  "bold",
] }
"ui.bufferline" = { fg = "textAlternate", bg = "backgroundAlternate" }
"ui.bufferline.active" = { fg = "background", bg = "primary", modifiers = [
  "bold",
] }
"ui.popup" = { fg = "textAlternate", bg = "backgroundAlternate" }
"ui.window" = { fg = "backgroundAlternate", bg = "transparent" }
"ui.help" = { fg = "text", bg = "backgroundAlternate" }
"ui.text" = "text"
"ui.text.focus" = "text"
"ui.menu" = { fg = "text", bg = "backgroundAlternate" }
"ui.menu.selected" = { fg = "background", bg = "textAlternate" }
"ui.virtual.ruler" = { bg = "backgroundAlternate" }
"ui.virtual.whitespace" = { fg = "backgroundAlternate" }
"ui.virtual.indent-guide" = { fg = "backgroundAlternate" }
"ui.virtual.inlay-hint" = { fg = "textAlternate" }
"ui.virtual.wrap" = { fg = "textAlternate" }

"hint" = "textAlternate"
"info" = "textAlternate"
"warning" = "textAlternate"
"error" = "textAlternate"

"diagnostic.hint" = { underline = { color = "textAlternate", style = "curl" } }
"diagnostic.info" = { underline = { color = "textAlternate", style = "curl" } }
"diagnostic.warning" = { underline = { color = "textAlternate", style = "curl" } }
"diagnostic.error" = { underline = { color = "textAlternate", style = "curl" } }
